import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({weight:["400", "500","600","700","800", "800"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <header className="h-[105px] bg-primary text-white flex items-center">
          <div className="container " data-cy="header-background">
			<h2 data-cy="header-title" className="uppercase text-[1.5rem] leading-[2.25rem] font-[700]">To do List App</h2>
		  </div>
        </header>
        {children}
      </body>
    </html>
  );
}
